events {}

http {

  upstream grpc_servers {
    server server1:50051;
    server server2:50051;
    server server3:50051;
  }

  server {
    listen 8080 http2;

    location / {
      grpc_pass grpc://grpc_servers;

      # Required for gRPC
      error_page 502 = /error502grpc;
    }

    location = /error502grpc {
      internal;
      default_type application/grpc;
      add_header grpc-status 14;
      add_header content-type application/grpc;
      return 204;
    }
  }
}